[plugins]
pkl = "https://github.com/chrisvander/asdf-pkl.git"

[tools]
pkl = "latest"
node = "18"
pnpm = "latest"

[tasks.pull-schema]
run = """
pkl eval package://pkg.pkl-lang.org/pkl-pantry/org.json_schema.contrib@1.0.3#/generate.pkl -m src -p source=\"https://biomejs.dev/schemas/$(cat version.txt)/schema.json\"
cat src/Schema.pkl | sed 's/(\\([A-Za-z0-9]*\\)|Any)/\\1/g' | sed 's/module Schema/module Biome/g' > src/Biome.pkl
rm src/Schema.pkl
"""
