name: Build & Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with: 
          experimental: true
      - name: Create Release
        uses: google-github-actions/release-please-action@v4
        id: release
      - name: Build Package
        run: |
          mise run pull-schema
          pkl project package src
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${{ steps.release.outputs.tag_name }}
          gh release upload ${{ steps.release.outputs.tag_name }} .out/$TAG/*
          gh release edit ${{ steps.release.outputs.tag_name }} -t ${{ steps.release.outputs.tag_name }}
      - name: Approve PR
        uses: hmarr/auto-approve-action@v4
        if: ${{ steps.release.outputs.prs_created }}
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          pull-request-number: ${{ steps.release.outputs.pr.number }}
